export const mapNames = [
  ["", "All Maps"],
  ["banana_depot_scene", "Banana Depot"],
  ["basalt_columns", "Basalt Columns"],
  ["building_site_scene", "Building Site"],
  ["bloon_bot_factory", "Bloon Bot Factory"],
  ["castle_ruins", "Castle Ruins"],
  ["cobra_command", "Cobra Command"],
  ["dino_graveyard", "Dino Graveyard"],
  ["garden", "Garden"],
  ["glade", "Glade"],
  ["inflection", "Inflection"],
  ["koru", "Koru"],
  ["oasis", "Oasis"],
  ["ports", "Ports"],
  ["sands_of_time", "Sands of Time"],
  ["star", "Star"],
  ["pirate_cove", "Pirate Cove"],
  ["precious_space", "Precious Space"],
  ["sun_palace", "Sun Palace"],
]

export const towerNames = {
  Alchemist: "Alchemist",
  BananaFarm: "Banana Farm",
  BombShooter: "Bomb Shooter",
  BoomerangMonkey: " Boomerang Monkey",
  DartMonkey: "Dart Monkey",
  DartlingGunner: "Dartling Gunner",
  Druid: "Druid",
  EngineerMonkey: "Engineer Monkey",
  GlueGunner: "Glue Gunner",
  HeliPilot: "Heli Pilot",
  IceMonkey: "Ice Monkey",
  MonkeyAce: "Monkey Ace",
  MonkeyBuccaneer: "Monkey Buccaneer",
  MonkeySub: "Monkey Sub",
  MonkeyVillage: "Monkey Village",
  MortarMonkey: "Mortar Monkey",
  NinjaMonkey: "Ninja Monkey",
  SniperMonkey: "Sniper Monkey",
  SpikeFactory: "Spike Factory",
  SuperMonkey: "Super Monkey",
  TackShooter: "Tack Shooter",
  WizardMonkey: "Wizard Monkey",
}

export const heroNames = {
  Quincy: "Quincy",
  Gwendolin_Science: "Scientist Gwendolin",
  Churchill_Sentai: "Sentai Churchill",
  Obyn: "Obyn Greenfoot",
  Gwendolin: "Gwendolin",
  StrikerJones: "Striker Jones",
  Benjamin_DJ: "DJ Benjamin",
  Obyn_Ocean: "Ocean Obyn",
  Churchill: "Captain Churchill",
  StrikerJones_Biker: "Biker Bones",
  PatFusty_Snowman: "Fusty the Snowman",
  Quincy_Cyber: "Cyber Quincy",
  Ezili: "Ezili",
  Benjamin: "Benjamin",
  Ezili_SmudgeCat: "Smudge Catt Ezili",
  PatFusty: "Pat Fusty",
  Jericho: "Agent Jericho",
  Jericho_Highwayman: "Highwayman Jericho",
  Jericho_StarCaptain: "Star Captain Jericho",
  Adora: "Adora",
}
